name: WordRush
main: io.github.InstaTrapCorp.wordrush.WordRush
version: 1.0
author: InstaTrapCorp
commands:
   lightup:
      description: Set people on fire
      usage: /lightup [player]
      permission: wordrush.lightup
      permission-message: You don't have wordrush.lightup